In [11]:
import numpy as np

In [12]:
np.version.version

'1.24.3'

In [13]:
a=np.array([0,1,2])

In [14]:
a

array([0, 1, 2])

In [15]:
v = np.zeros(6)

In [16]:
v

array([0., 0., 0., 0., 0., 0.])

In [17]:
np.arange(3,15,.5)

array([ 3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,
        8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5,
       14. , 14.5])

In [18]:
Q= [0,1,2]
#l.append([3,4,5])

In [19]:
Q+[3,4,5]

[0, 1, 2, 3, 4, 5]

In [20]:
np.append(Q,[3,4,5])

array([0, 1, 2, 3, 4, 5])

In [21]:
# a =np.delete(a,1)

In [22]:
a2 = np.array([6,9,4,3,2,1,7,12,8,0,5,5])

In [23]:
np.sort(a2)

array([ 0,  1,  2,  3,  4,  5,  5,  6,  7,  8,  9, 12])

In [24]:
matrix = np.array([
    [0,  1,  2], 
    [3,  4,  5], 
    [5,  6,  7], 
    [8,  9, 12]
])

In [25]:
matrix.ndim

2

In [26]:
matrix.size

12

In [27]:
matrix.shape

(4, 3)

In [28]:
a2.shape

(12,)

In [29]:
a2.reshape(12,1)

array([[ 6],
       [ 9],
       [ 4],
       [ 3],
       [ 2],
       [ 1],
       [ 7],
       [12],
       [ 8],
       [ 0],
       [ 5],
       [ 5]])

In [30]:
a2.reshape(1,12)

array([[ 6,  9,  4,  3,  2,  1,  7, 12,  8,  0,  5,  5]])

In [31]:
a2.reshape(3,4)

array([[ 6,  9,  4,  3],
       [ 2,  1,  7, 12],
       [ 8,  0,  5,  5]])

In [32]:
a2.reshape(4,3)

array([[ 6,  9,  4],
       [ 3,  2,  1],
       [ 7, 12,  8],
       [ 0,  5,  5]])

In [33]:
a2.reshape(6,2)

array([[ 6,  9],
       [ 4,  3],
       [ 2,  1],
       [ 7, 12],
       [ 8,  0],
       [ 5,  5]])

In [34]:
a2.reshape(2,6)

array([[ 6,  9,  4,  3,  2,  1],
       [ 7, 12,  8,  0,  5,  5]])

In [35]:
a3= np.arange(8)

In [36]:
a3.size

8

In [37]:
a3.reshape(1,8)

array([[0, 1, 2, 3, 4, 5, 6, 7]])

In [38]:
a3.reshape(8,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [39]:
a3.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [40]:
a3.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [41]:
a2[np.newaxis]

array([[ 6,  9,  4,  3,  2,  1,  7, 12,  8,  0,  5,  5]])

In [42]:
a2[:,np.newaxis]

array([[ 6],
       [ 9],
       [ 4],
       [ 3],
       [ 2],
       [ 1],
       [ 7],
       [12],
       [ 8],
       [ 0],
       [ 5],
       [ 5]])

In [43]:
a2[:,np.newaxis].shape

(12, 1)

In [44]:
a2

array([ 6,  9,  4,  3,  2,  1,  7, 12,  8,  0,  5,  5])

In [45]:
np.expand_dims(a2,axis=0)

array([[ 6,  9,  4,  3,  2,  1,  7, 12,  8,  0,  5,  5]])

In [46]:
np.expand_dims(a2,axis=1)

array([[ 6],
       [ 9],
       [ 4],
       [ 3],
       [ 2],
       [ 1],
       [ 7],
       [12],
       [ 8],
       [ 0],
       [ 5],
       [ 5]])

In [47]:
mat=a2.reshape(3,4)

In [48]:
a2

array([ 6,  9,  4,  3,  2,  1,  7, 12,  8,  0,  5,  5])

In [49]:
a2[7]

12

In [50]:
mat

array([[ 6,  9,  4,  3],
       [ 2,  1,  7, 12],
       [ 8,  0,  5,  5]])

In [51]:
mat[2,3]

5

In [52]:
a2

array([ 6,  9,  4,  3,  2,  1,  7, 12,  8,  0,  5,  5])

In [53]:
a2[1:4]

array([9, 4, 3])

In [54]:
a2[-2:]

array([5, 5])

In [55]:
a2[:-2]

array([ 6,  9,  4,  3,  2,  1,  7, 12,  8,  0])

In [56]:
mat[1:,:]

array([[ 2,  1,  7, 12],
       [ 8,  0,  5,  5]])

In [57]:
a2>=8

array([False,  True, False, False, False, False, False,  True,  True,
       False, False, False])

In [58]:
a2[a2>=8]

array([ 9, 12,  8])

In [59]:
a2[(a2>3)&(a2<6)]

array([4, 5, 5])

In [60]:
arr = np.arange(11,21)
arr2 = np.arange(21,31)

In [61]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [62]:
arr2

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [63]:
np.vstack((arr,arr2))

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [92]:
mat1=np.arange(4).reshape(2,2)
mat2=np.arange(8,12).reshape(2,2)

In [93]:
mat1

array([[0, 1],
       [2, 3]])

In [94]:
mat2

array([[ 8,  9],
       [10, 11]])

In [95]:
np.vstack((mat2,mat1))

array([[ 8,  9],
       [10, 11],
       [ 0,  1],
       [ 2,  3]])

In [96]:
mat1

array([[0, 1],
       [2, 3]])

In [97]:
mat2

array([[ 8,  9],
       [10, 11]])

In [98]:
mat3=np.arange(9).reshape(3,3)
mat4=np.arange(9,15).reshape(3,2)

In [99]:
mat3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [100]:
mat4

array([[ 9, 10],
       [11, 12],
       [13, 14]])

In [101]:
np.hstack((mat3,mat4))

array([[ 0,  1,  2,  9, 10],
       [ 3,  4,  5, 11, 12],
       [ 6,  7,  8, 13, 14]])

In [102]:
np.hsplit(mat3,3)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [103]:
a1= np.arange(1,16)
a2=np.arange(16,31)

In [104]:
print(a1)
print(a2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


In [105]:
a1+a2

array([17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45])

In [106]:
a2 - a1

array([15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15])

In [107]:
a2/a1

array([16.        ,  8.5       ,  6.        ,  4.75      ,  4.        ,
        3.5       ,  3.14285714,  2.875     ,  2.66666667,  2.5       ,
        2.36363636,  2.25      ,  2.15384615,  2.07142857,  2.        ])

In [108]:
a2*a1

array([ 16,  34,  54,  76, 100, 126, 154, 184, 216, 250, 286, 324, 364,
       406, 450])

In [109]:
mat1

array([[0, 1],
       [2, 3]])

In [110]:
mat2_n=mat2[:4,:]

In [111]:
mat2_n

array([[ 8,  9],
       [10, 11]])

In [112]:
mat1+mat2_n

array([[ 8, 10],
       [12, 14]])

In [113]:
mat1*mat2_n

array([[ 0,  9],
       [20, 33]])

In [114]:
a1 + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [115]:
a1  / 3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667,
       2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
       3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ])

In [116]:
mat3 % 4

array([[0, 1, 2],
       [3, 0, 1],
       [2, 3, 0]], dtype=int32)

In [117]:
mat3.sum()

36

In [118]:
a2.sum()

345

In [119]:
mat3.max()

8

In [120]:
a2.min()

16

In [122]:
mat3.min()

0

In [123]:
mat3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [124]:
mat3.max(axis=1)

array([2, 5, 8])

In [125]:
mat3.sum(axis=1)

array([ 3, 12, 21])

In [126]:
mat3.std()

2.581988897471611

In [127]:
mat3.mean(axis=0)

array([3., 4., 5.])

In [128]:
mat3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [129]:
mat4

array([[ 9, 10],
       [11, 12],
       [13, 14]])

In [130]:
np.dot(mat3,mat4)

array([[ 37,  40],
       [136, 148],
       [235, 256]])

In [131]:
mat3 @ mat4

array([[ 37,  40],
       [136, 148],
       [235, 256]])

In [132]:
np.random.randn(10)

array([-1.04284326,  0.62489756,  0.50832313,  1.63463087, -0.62627483,
        0.91037368,  0.20282601,  0.81701315, -0.82239405, -1.1935762 ])

In [138]:
np.linalg.inv(mat3.reshape(3,3))

LinAlgError: Singular matrix

In [139]:
np.linalg.inv(np.array([[1.,2.], [3.,4.]]))

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [140]:
nd=np.arange(8).reshape(2,2,2)

In [141]:
nd.ndim

3

In [142]:
nd.shape

(2, 2, 2)

In [143]:
nd[0,0,0]

0

In [144]:
mat.flatten()

array([ 6,  9,  4,  3,  2,  1,  7, 12,  8,  0,  5,  5])